version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: events_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/events-app-back
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # volumes:
    #   - ./backend/events-app-back:/app
    depends_on:
      - postgres

  client:
    build:
      context: ./events-app-client
      dockerfile: Dockerfile.dev
    working_dir: /usr/src/app/node_modules
    command: ["./@angular/cli/bin/ng", "serve", "--host", "0.0.0.0"]
    ports:
      - "8080:4200"
    volumes:
      - ./events-app-client:/usr/src/app
    depends_on:
      - backend

volumes:
  postgres_data:
